### ISSUE TITLE
Couldn't load the account balance due to Error response from the server

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/threefold_connect#766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The debug console won't stop logging the following err:

![image](https://github.com/user-attachments/assets/9182f370-044f-45eb-bd31-d8e0686ab8f0)

### Steps To Reproduce

1. Login
2. Open wallets

### Relevant screenshots/screen records

-

### Relevant log output

```console
/flutter (11522): │ #0   getBalanceByClient (package:threebotlogin/services/stellar_service.dart:37:12)
I/flutter (11522): │ #1   <asynchronous suspension>
I/flutter (11522): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (11522): │ 11:08:06.912 (+0:08:31.962098)
I/flutter (11522): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (11522): │ 💡 Couldn't load the account balance due to Error response from the server. Code: 404 - Body: {
I/flutter (11522): │ 💡   "type": "https://stellar.org/horizon-errors/not_found",
I/flutter (11522): │ 💡   "title": "Resource Missing",
I/flutter (11522): │ 💡   "status": 404,
I/flutter (11522): │ 💡   "detail": "The resource at the url requested was not found.  This usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided."
I/flutter (11522): │ 💡 }
I/flutter (11522): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (11522): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (11522): │ #0   getBalanceByClient (package:threebotlogin/services/stellar_service.dart:37:12)
I/flutter (11522): │ #1   <asynchronous suspension>
I/flutter (11522): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (11522): │ 11:08:21.063 (+0:08:46.112904)
I/flutter (11522): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (11522): │ 💡 Couldn't load the account balance due to Error response from the server. Code: 404 - Body: {
I/flutter (11522): │ 💡   "type": "https://stellar.org/horizon-errors/not_found",
I/flutter (11522): │ 💡   "title": "Resource Missing",
I/flutter (11522): │ 💡   "status": 404,
I/flutter (11522): │ 💡   "detail": "The resource at the url requested was not found.  This usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided."
I/flutter (11522): │ 💡 }
I/flutter (11522): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (11522): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (11522): │ #0   getBalanceByClient (package:threebotlogin/services/stellar_service.dart:37:12)
I/flutter (11522): │ #1   <asynchronous suspension>
I/flutter (11522): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (11522): │ 11:08:35.131 (+0:09:00.181426)
I/flutter (11522): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (11522): │ 💡 Couldn't load the account balance due to Error response from the server. Code: 404 - Body: {
I/flutter (11522): │ 💡   "type": "https://stellar.org/horizon-errors/not_found",
I/flutter (11522): │ 💡   "title": "Resource Missing",
I/flutter (11522): │ 💡   "status": 404,
I/flutter (11522): │ 💡   "detail": "The resource at the url requested was not found.  This usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided."
I/flutter (11522): │ 💡 }
I/flutter (11522): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (11522): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (11522): │ #0   getBalanceByClient (package:threebotlogin/services/stellar_service.dart:37:12)
I/flutter (11522): │ #1   <asynchronous suspension>
I/flutter (11522): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (11522): │ 11:08:49.215 (+0:09:14.264715)
I/flutter (11522): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (11522): │ 💡 Couldn't load the account balance due to Error response from the server. Code: 404 - Body: {
I/flutter (11522): │ 💡   "type": "https://stellar.org/horizon-errors/not_found",
I/flutter (11522): │ 💡   "title": "Resource Missing",
I/flutter (11522): │ 💡   "status": 404,
I/flutter (11522): │ 💡   "detail": "The resource at the url requested was not found.  This usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided."
I/flutter (11522): │ 💡 }
I/flutter (11522): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (11522): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (11522): │ #0   getBalanceByClient (package:threebotlogin/services/stellar_service.dart:37:12)
I/flutter (11522): │ #1   <asynchronous suspension>
I/flutter (11522): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (11522): │ 11:09:03.183 (+0:09:28.233189)
I/flutter (11522): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (11522): │ 💡 Couldn't load the account balance due to Error response from the server. Code: 404 - Body: {
I/flutter (11522): │ 💡   "type": "https://stellar.org/horizon-errors/not_found",
I/flutter (11522): │ 💡   "title": "Resource Missing",
I/flutter (11522): │ 💡   "status": 404,
I/flutter (11522): │ 💡   "detail": "The resource at the url requested was not found.  This usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided."
I/flutter (11522): │ 💡 }
I/flutter (11522): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (11522): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (11522): │ #0   getBalanceByClient (package:threebotlogin/services/stellar_service.dart:37:12)
I/flutter (11522): │ #1   <asynchronous suspension>
I/flutter (11522): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (11522): │ 11:09:17.329 (+0:09:42.379395)
I/flutter (11522): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (11522): │ 💡 Couldn't load the account balance due to Error response from the server. Code: 404 - Body: {
I/flutter (11522): │ 💡   "type": "https://stellar.org/horizon-errors/not_found",
I/flutter (11522): │ 💡   "title": "Resource Missing",
I/flutter (11522): │ 💡   "status": 404,
I/flutter (11522): │ 💡   "detail": "The resource at the url requested was not found.  This usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided."
I/flutter (11522): │ 💡 }
I/flutter (11522): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```
```

**Comment by AhmedHanafy725** [comment]
the logs are normal as there might be some wallets that are not activated on stellar
