### ISSUE TITLE
Error while log in

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/threefold_connect#832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/user-attachments/assets/727e038b-85cf-4f20-b040-566c4c5f6aac)

### Relevant screenshots/screen records

-

### Relevant log output

```console
E/flutter (31701): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: setState() called after dispose(): _PreferenceScreenState#6cd0b(lifecycle state: defunct, not mounted)
E/flutter (31701): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter (31701): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (31701): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (31701): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1167:9)
E/flutter (31701): #1      State.setState (package:flutter/src/widgets/framework.dart:1202:6)
E/flutter (31701): #2      _PreferenceScreenState._showDialog.<anonymous closure>.<anonymous closure> (package:threebotlogin/screens/preference_screen.dart:362:11)
E/flutter (31701): <asynchronous suspension>
E/flutter (31701): #3      _WarningDialogWidgetState.build.<anonymous closure> (package:threebotlogin/widgets/wallets/warning_dialog.dart:40:13)
E/flutter (31701): <asynchronous suspension>
E/flutter (31701): 
```
```

**Comment by Fonseca624** [comment]
Hello @zaelgohary  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by zaelgohary** [comment]
Work completed:

Checked if widget is mounted before setState, assured async operation finished before pop context.

**Comment by khaledyoussef24** [comment]
verified on IOS 18
version 4.0.1 -185

now the loading process works perfectly 
the loading time is minimized in the farms and wallets

![Image](https://github.com/user-attachments/assets/98b2212a-d640-4447-af53-3c4f0c1a23d9)

![Image](https://github.com/user-attachments/assets/6c51d781-897a-4139-9c3c-c36b5dff4bc2)

https://github.com/user-attachments/assets/9273a7a4-388f-4665-bde6-59a0ee266707
